// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9rWvW0yZYcu3LDdKRV5IdsW2Ugx3jjLQ',
    appId: '1:325137610876:web:a8478687daa9b710c431f9',
    messagingSenderId: '325137610876',
    projectId: 'triviaia',
    authDomain: 'triviaia.firebaseapp.com',
    storageBucket: 'triviaia.firebasestorage.app',
    measurementId: 'G-K3JTF82JVY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxz-QOb_B0zKbe8iWr5pSYRLwOuAHEKqQ',
    appId: '1:325137610876:android:1725705ad135b1b7c431f9',
    messagingSenderId: '325137610876',
    projectId: 'triviaia',
    storageBucket: 'triviaia.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCm13F9xyfcEHh-7EvJu5ud5_R7lHdhmj0',
    appId: '1:325137610876:ios:2279c1f45c1bfc4ec431f9',
    messagingSenderId: '325137610876',
    projectId: 'triviaia',
    storageBucket: 'triviaia.firebasestorage.app',
    iosBundleId: 'y',
  );

}